\begin{multicols}{6}
\small
\noindent \texttt{ 1111 } acid \par
\noindent \texttt{ \ \ \ 2 } acorn \par
\noindent \texttt{ \ \ \ 3 } acre \par
\noindent \texttt{ \ \ \ 4 } acts \par
\noindent \texttt{ \ \ \ 5 } afar \par
\noindent \texttt{ \ \ \ 6 } affix \par
\groupsep
\noindent \texttt{ 1121 } aged \par
\noindent \texttt{ \ \ \ 2 } agent \par
\noindent \texttt{ \ \ \ 3 } agile \par
\noindent \texttt{ \ \ \ 4 } aging \par
\noindent \texttt{ \ \ \ 5 } agony \par
\noindent \texttt{ \ \ \ 6 } ahead \par
\groupsep
\noindent \texttt{ 1131 } aide \par
\noindent \texttt{ \ \ \ 2 } aids \par
\noindent \texttt{ \ \ \ 3 } aim \par
\noindent \texttt{ \ \ \ 4 } ajar \par
\noindent \texttt{ \ \ \ 5 } alarm \par
\noindent \texttt{ \ \ \ 6 } alias \par
\groupsep
\noindent \texttt{ 1141 } alibi \par
\noindent \texttt{ \ \ \ 2 } alien \par
\noindent \texttt{ \ \ \ 3 } alike \par
\noindent \texttt{ \ \ \ 4 } alive \par
\noindent \texttt{ \ \ \ 5 } aloe \par
\noindent \texttt{ \ \ \ 6 } aloft \par
\groupsep
\noindent \texttt{ 1151 } aloha \par
\noindent \texttt{ \ \ \ 2 } alone \par
\noindent \texttt{ \ \ \ 3 } amend \par
\noindent \texttt{ \ \ \ 4 } amino \par
\noindent \texttt{ \ \ \ 5 } ample \par
\noindent \texttt{ \ \ \ 6 } amuse \par
\groupsep
\noindent \texttt{ 1161 } angel \par
\noindent \texttt{ \ \ \ 2 } anger \par
\noindent \texttt{ \ \ \ 3 } angle \par
\noindent \texttt{ \ \ \ 4 } ankle \par
\noindent \texttt{ \ \ \ 5 } apple \par
\noindent \texttt{ \ \ \ 6 } april \par
\noindent \texttt{ 1211 } apron \par
\noindent \texttt{ \ \ \ 2 } aqua \par
\noindent \texttt{ \ \ \ 3 } area \par
\noindent \texttt{ \ \ \ 4 } arena \par
\noindent \texttt{ \ \ \ 5 } argue \par
\noindent \texttt{ \ \ \ 6 } arise \par
\groupsep
\noindent \texttt{ 1221 } armed \par
\noindent \texttt{ \ \ \ 2 } armor \par
\noindent \texttt{ \ \ \ 3 } army \par
\noindent \texttt{ \ \ \ 4 } aroma \par
\noindent \texttt{ \ \ \ 5 } array \par
\noindent \texttt{ \ \ \ 6 } arson \par
\groupsep
\noindent \texttt{ 1231 } art \par
\noindent \texttt{ \ \ \ 2 } ashen \par
\noindent \texttt{ \ \ \ 3 } ashes \par
\noindent \texttt{ \ \ \ 4 } atlas \par
\noindent \texttt{ \ \ \ 5 } atom \par
\noindent \texttt{ \ \ \ 6 } attic \par
\groupsep
\noindent \texttt{ 1241 } audio \par
\noindent \texttt{ \ \ \ 2 } avert \par
\noindent \texttt{ \ \ \ 3 } avoid \par
\noindent \texttt{ \ \ \ 4 } awake \par
\noindent \texttt{ \ \ \ 5 } award \par
\noindent \texttt{ \ \ \ 6 } awoke \par
\groupsep
\noindent \texttt{ 1251 } axis \par
\noindent \texttt{ \ \ \ 2 } bacon \par
\noindent \texttt{ \ \ \ 3 } badge \par
\noindent \texttt{ \ \ \ 4 } bagel \par
\noindent \texttt{ \ \ \ 5 } baggy \par
\noindent \texttt{ \ \ \ 6 } baked \par
\groupsep
\noindent \texttt{ 1261 } baker \par
\noindent \texttt{ \ \ \ 2 } balmy \par
\noindent \texttt{ \ \ \ 3 } banjo \par
\noindent \texttt{ \ \ \ 4 } barge \par
\noindent \texttt{ \ \ \ 5 } barn \par
\noindent \texttt{ \ \ \ 6 } bash \par
\noindent \texttt{ 1311 } basil \par
\noindent \texttt{ \ \ \ 2 } bask \par
\noindent \texttt{ \ \ \ 3 } batch \par
\noindent \texttt{ \ \ \ 4 } bath \par
\noindent \texttt{ \ \ \ 5 } baton \par
\noindent \texttt{ \ \ \ 6 } bats \par
\groupsep
\noindent \texttt{ 1321 } blade \par
\noindent \texttt{ \ \ \ 2 } blank \par
\noindent \texttt{ \ \ \ 3 } blast \par
\noindent \texttt{ \ \ \ 4 } blaze \par
\noindent \texttt{ \ \ \ 5 } bleak \par
\noindent \texttt{ \ \ \ 6 } blend \par
\groupsep
\noindent \texttt{ 1331 } bless \par
\noindent \texttt{ \ \ \ 2 } blimp \par
\noindent \texttt{ \ \ \ 3 } blink \par
\noindent \texttt{ \ \ \ 4 } bloat \par
\noindent \texttt{ \ \ \ 5 } blob \par
\noindent \texttt{ \ \ \ 6 } blog \par
\groupsep
\noindent \texttt{ 1341 } blot \par
\noindent \texttt{ \ \ \ 2 } blunt \par
\noindent \texttt{ \ \ \ 3 } blurt \par
\noindent \texttt{ \ \ \ 4 } blush \par
\noindent \texttt{ \ \ \ 5 } boast \par
\noindent \texttt{ \ \ \ 6 } boat \par
\groupsep
\noindent \texttt{ 1351 } body \par
\noindent \texttt{ \ \ \ 2 } boil \par
\noindent \texttt{ \ \ \ 3 } bok \par
\noindent \texttt{ \ \ \ 4 } bolt \par
\noindent \texttt{ \ \ \ 5 } boned \par
\noindent \texttt{ \ \ \ 6 } boney \par
\groupsep
\noindent \texttt{ 1361 } bonus \par
\noindent \texttt{ \ \ \ 2 } bony \par
\noindent \texttt{ \ \ \ 3 } book \par
\noindent \texttt{ \ \ \ 4 } booth \par
\noindent \texttt{ \ \ \ 5 } boots \par
\noindent \texttt{ \ \ \ 6 } boss \par
\noindent \texttt{ 1411 } botch \par
\noindent \texttt{ \ \ \ 2 } both \par
\noindent \texttt{ \ \ \ 3 } boxer \par
\noindent \texttt{ \ \ \ 4 } breed \par
\noindent \texttt{ \ \ \ 5 } bribe \par
\noindent \texttt{ \ \ \ 6 } brick \par
\groupsep
\noindent \texttt{ 1421 } bride \par
\noindent \texttt{ \ \ \ 2 } brim \par
\noindent \texttt{ \ \ \ 3 } bring \par
\noindent \texttt{ \ \ \ 4 } brink \par
\noindent \texttt{ \ \ \ 5 } brisk \par
\noindent \texttt{ \ \ \ 6 } broad \par
\groupsep
\noindent \texttt{ 1431 } broil \par
\noindent \texttt{ \ \ \ 2 } broke \par
\noindent \texttt{ \ \ \ 3 } brook \par
\noindent \texttt{ \ \ \ 4 } broom \par
\noindent \texttt{ \ \ \ 5 } brush \par
\noindent \texttt{ \ \ \ 6 } buck \par
\groupsep
\noindent \texttt{ 1441 } bud \par
\noindent \texttt{ \ \ \ 2 } buggy \par
\noindent \texttt{ \ \ \ 3 } bulge \par
\noindent \texttt{ \ \ \ 4 } bulk \par
\noindent \texttt{ \ \ \ 5 } bully \par
\noindent \texttt{ \ \ \ 6 } bunch \par
\groupsep
\noindent \texttt{ 1451 } bunny \par
\noindent \texttt{ \ \ \ 2 } bunt \par
\noindent \texttt{ \ \ \ 3 } bush \par
\noindent \texttt{ \ \ \ 4 } bust \par
\noindent \texttt{ \ \ \ 5 } busy \par
\noindent \texttt{ \ \ \ 6 } buzz \par
\groupsep
\noindent \texttt{ 1461 } cable \par
\noindent \texttt{ \ \ \ 2 } cache \par
\noindent \texttt{ \ \ \ 3 } cadet \par
\noindent \texttt{ \ \ \ 4 } cage \par
\noindent \texttt{ \ \ \ 5 } cake \par
\noindent \texttt{ \ \ \ 6 } calm \par
\noindent \texttt{ 1511 } cameo \par
\noindent \texttt{ \ \ \ 2 } canal \par
\noindent \texttt{ \ \ \ 3 } candy \par
\noindent \texttt{ \ \ \ 4 } cane \par
\noindent \texttt{ \ \ \ 5 } canon \par
\noindent \texttt{ \ \ \ 6 } cape \par
\groupsep
\noindent \texttt{ 1521 } card \par
\noindent \texttt{ \ \ \ 2 } cargo \par
\noindent \texttt{ \ \ \ 3 } carol \par
\noindent \texttt{ \ \ \ 4 } carry \par
\noindent \texttt{ \ \ \ 5 } carve \par
\noindent \texttt{ \ \ \ 6 } case \par
\groupsep
\noindent \texttt{ 1531 } cash \par
\noindent \texttt{ \ \ \ 2 } cause \par
\noindent \texttt{ \ \ \ 3 } cedar \par
\noindent \texttt{ \ \ \ 4 } chain \par
\noindent \texttt{ \ \ \ 5 } chair \par
\noindent \texttt{ \ \ \ 6 } chant \par
\groupsep
\noindent \texttt{ 1541 } chaos \par
\noindent \texttt{ \ \ \ 2 } charm \par
\noindent \texttt{ \ \ \ 3 } chase \par
\noindent \texttt{ \ \ \ 4 } cheek \par
\noindent \texttt{ \ \ \ 5 } cheer \par
\noindent \texttt{ \ \ \ 6 } chef \par
\groupsep
\noindent \texttt{ 1551 } chess \par
\noindent \texttt{ \ \ \ 2 } chest \par
\noindent \texttt{ \ \ \ 3 } chew \par
\noindent \texttt{ \ \ \ 4 } chief \par
\noindent \texttt{ \ \ \ 5 } chili \par
\noindent \texttt{ \ \ \ 6 } chill \par
\groupsep
\noindent \texttt{ 1561 } chip \par
\noindent \texttt{ \ \ \ 2 } chomp \par
\noindent \texttt{ \ \ \ 3 } chop \par
\noindent \texttt{ \ \ \ 4 } chow \par
\noindent \texttt{ \ \ \ 5 } chuck \par
\noindent \texttt{ \ \ \ 6 } chump \par
\noindent \texttt{ 1611 } chunk \par
\noindent \texttt{ \ \ \ 2 } churn \par
\noindent \texttt{ \ \ \ 3 } chute \par
\noindent \texttt{ \ \ \ 4 } cider \par
\noindent \texttt{ \ \ \ 5 } cinch \par
\noindent \texttt{ \ \ \ 6 } city \par
\groupsep
\noindent \texttt{ 1621 } civic \par
\noindent \texttt{ \ \ \ 2 } civil \par
\noindent \texttt{ \ \ \ 3 } clad \par
\noindent \texttt{ \ \ \ 4 } claim \par
\noindent \texttt{ \ \ \ 5 } clamp \par
\noindent \texttt{ \ \ \ 6 } clap \par
\groupsep
\noindent \texttt{ 1631 } clash \par
\noindent \texttt{ \ \ \ 2 } clasp \par
\noindent \texttt{ \ \ \ 3 } class \par
\noindent \texttt{ \ \ \ 4 } claw \par
\noindent \texttt{ \ \ \ 5 } clay \par
\noindent \texttt{ \ \ \ 6 } clean \par
\groupsep
\noindent \texttt{ 1641 } clear \par
\noindent \texttt{ \ \ \ 2 } cleat \par
\noindent \texttt{ \ \ \ 3 } cleft \par
\noindent \texttt{ \ \ \ 4 } clerk \par
\noindent \texttt{ \ \ \ 5 } click \par
\noindent \texttt{ \ \ \ 6 } cling \par
\groupsep
\noindent \texttt{ 1651 } clink \par
\noindent \texttt{ \ \ \ 2 } clip \par
\noindent \texttt{ \ \ \ 3 } cloak \par
\noindent \texttt{ \ \ \ 4 } clock \par
\noindent \texttt{ \ \ \ 5 } clone \par
\noindent \texttt{ \ \ \ 6 } cloth \par
\groupsep
\noindent \texttt{ 1661 } cloud \par
\noindent \texttt{ \ \ \ 2 } clump \par
\noindent \texttt{ \ \ \ 3 } coach \par
\noindent \texttt{ \ \ \ 4 } coast \par
\noindent \texttt{ \ \ \ 5 } coat \par
\noindent \texttt{ \ \ \ 6 } cod \par
\end{multicols}
\begin{multicols}{6}
\small
\noindent \texttt{ 2111 } coil \par
\noindent \texttt{ \ \ \ 2 } coke \par
\noindent \texttt{ \ \ \ 3 } cola \par
\noindent \texttt{ \ \ \ 4 } cold \par
\noindent \texttt{ \ \ \ 5 } colt \par
\noindent \texttt{ \ \ \ 6 } coma \par
\groupsep
\noindent \texttt{ 2121 } come \par
\noindent \texttt{ \ \ \ 2 } comic \par
\noindent \texttt{ \ \ \ 3 } comma \par
\noindent \texttt{ \ \ \ 4 } cone \par
\noindent \texttt{ \ \ \ 5 } cope \par
\noindent \texttt{ \ \ \ 6 } copy \par
\groupsep
\noindent \texttt{ 2131 } coral \par
\noindent \texttt{ \ \ \ 2 } cork \par
\noindent \texttt{ \ \ \ 3 } cost \par
\noindent \texttt{ \ \ \ 4 } cot \par
\noindent \texttt{ \ \ \ 5 } couch \par
\noindent \texttt{ \ \ \ 6 } cough \par
\groupsep
\noindent \texttt{ 2141 } cover \par
\noindent \texttt{ \ \ \ 2 } cozy \par
\noindent \texttt{ \ \ \ 3 } craft \par
\noindent \texttt{ \ \ \ 4 } cramp \par
\noindent \texttt{ \ \ \ 5 } crane \par
\noindent \texttt{ \ \ \ 6 } crank \par
\groupsep
\noindent \texttt{ 2151 } crate \par
\noindent \texttt{ \ \ \ 2 } crave \par
\noindent \texttt{ \ \ \ 3 } crawl \par
\noindent \texttt{ \ \ \ 4 } crazy \par
\noindent \texttt{ \ \ \ 5 } creme \par
\noindent \texttt{ \ \ \ 6 } crepe \par
\groupsep
\noindent \texttt{ 2161 } crept \par
\noindent \texttt{ \ \ \ 2 } crib \par
\noindent \texttt{ \ \ \ 3 } cried \par
\noindent \texttt{ \ \ \ 4 } crisp \par
\noindent \texttt{ \ \ \ 5 } crook \par
\noindent \texttt{ \ \ \ 6 } crop \par
\noindent \texttt{ 2211 } cross \par
\noindent \texttt{ \ \ \ 2 } crowd \par
\noindent \texttt{ \ \ \ 3 } crown \par
\noindent \texttt{ \ \ \ 4 } crumb \par
\noindent \texttt{ \ \ \ 5 } crush \par
\noindent \texttt{ \ \ \ 6 } crust \par
\groupsep
\noindent \texttt{ 2221 } cub \par
\noindent \texttt{ \ \ \ 2 } cult \par
\noindent \texttt{ \ \ \ 3 } cupid \par
\noindent \texttt{ \ \ \ 4 } cure \par
\noindent \texttt{ \ \ \ 5 } curl \par
\noindent \texttt{ \ \ \ 6 } curry \par
\groupsep
\noindent \texttt{ 2231 } curse \par
\noindent \texttt{ \ \ \ 2 } curve \par
\noindent \texttt{ \ \ \ 3 } curvy \par
\noindent \texttt{ \ \ \ 4 } cushy \par
\noindent \texttt{ \ \ \ 5 } cut \par
\noindent \texttt{ \ \ \ 6 } cycle \par
\groupsep
\noindent \texttt{ 2241 } dab \par
\noindent \texttt{ \ \ \ 2 } dad \par
\noindent \texttt{ \ \ \ 3 } daily \par
\noindent \texttt{ \ \ \ 4 } dairy \par
\noindent \texttt{ \ \ \ 5 } daisy \par
\noindent \texttt{ \ \ \ 6 } dance \par
\groupsep
\noindent \texttt{ 2251 } dandy \par
\noindent \texttt{ \ \ \ 2 } darn \par
\noindent \texttt{ \ \ \ 3 } dart \par
\noindent \texttt{ \ \ \ 4 } dash \par
\noindent \texttt{ \ \ \ 5 } data \par
\noindent \texttt{ \ \ \ 6 } date \par
\groupsep
\noindent \texttt{ 2261 } dawn \par
\noindent \texttt{ \ \ \ 2 } deaf \par
\noindent \texttt{ \ \ \ 3 } deal \par
\noindent \texttt{ \ \ \ 4 } dean \par
\noindent \texttt{ \ \ \ 5 } debit \par
\noindent \texttt{ \ \ \ 6 } debt \par
\noindent \texttt{ 2311 } debug \par
\noindent \texttt{ \ \ \ 2 } decaf \par
\noindent \texttt{ \ \ \ 3 } decal \par
\noindent \texttt{ \ \ \ 4 } decay \par
\noindent \texttt{ \ \ \ 5 } deck \par
\noindent \texttt{ \ \ \ 6 } decor \par
\groupsep
\noindent \texttt{ 2321 } decoy \par
\noindent \texttt{ \ \ \ 2 } deed \par
\noindent \texttt{ \ \ \ 3 } delay \par
\noindent \texttt{ \ \ \ 4 } denim \par
\noindent \texttt{ \ \ \ 5 } dense \par
\noindent \texttt{ \ \ \ 6 } dent \par
\groupsep
\noindent \texttt{ 2331 } depth \par
\noindent \texttt{ \ \ \ 2 } derby \par
\noindent \texttt{ \ \ \ 3 } desk \par
\noindent \texttt{ \ \ \ 4 } dial \par
\noindent \texttt{ \ \ \ 5 } diary \par
\noindent \texttt{ \ \ \ 6 } dice \par
\groupsep
\noindent \texttt{ 2341 } dig \par
\noindent \texttt{ \ \ \ 2 } dill \par
\noindent \texttt{ \ \ \ 3 } dime \par
\noindent \texttt{ \ \ \ 4 } dimly \par
\noindent \texttt{ \ \ \ 5 } diner \par
\noindent \texttt{ \ \ \ 6 } dingy \par
\groupsep
\noindent \texttt{ 2351 } disco \par
\noindent \texttt{ \ \ \ 2 } dish \par
\noindent \texttt{ \ \ \ 3 } disk \par
\noindent \texttt{ \ \ \ 4 } ditch \par
\noindent \texttt{ \ \ \ 5 } ditzy \par
\noindent \texttt{ \ \ \ 6 } dizzy \par
\groupsep
\noindent \texttt{ 2361 } dock \par
\noindent \texttt{ \ \ \ 2 } dodge \par
\noindent \texttt{ \ \ \ 3 } doing \par
\noindent \texttt{ \ \ \ 4 } doll \par
\noindent \texttt{ \ \ \ 5 } dome \par
\noindent \texttt{ \ \ \ 6 } donor \par
\noindent \texttt{ 2411 } donut \par
\noindent \texttt{ \ \ \ 2 } dose \par
\noindent \texttt{ \ \ \ 3 } dot \par
\noindent \texttt{ \ \ \ 4 } dove \par
\noindent \texttt{ \ \ \ 5 } down \par
\noindent \texttt{ \ \ \ 6 } dowry \par
\groupsep
\noindent \texttt{ 2421 } doze \par
\noindent \texttt{ \ \ \ 2 } drab \par
\noindent \texttt{ \ \ \ 3 } drama \par
\noindent \texttt{ \ \ \ 4 } drank \par
\noindent \texttt{ \ \ \ 5 } draw \par
\noindent \texttt{ \ \ \ 6 } dress \par
\groupsep
\noindent \texttt{ 2431 } dried \par
\noindent \texttt{ \ \ \ 2 } drift \par
\noindent \texttt{ \ \ \ 3 } drill \par
\noindent \texttt{ \ \ \ 4 } drive \par
\noindent \texttt{ \ \ \ 5 } drone \par
\noindent \texttt{ \ \ \ 6 } droop \par
\groupsep
\noindent \texttt{ 2441 } drove \par
\noindent \texttt{ \ \ \ 2 } drown \par
\noindent \texttt{ \ \ \ 3 } drum \par
\noindent \texttt{ \ \ \ 4 } dry \par
\noindent \texttt{ \ \ \ 5 } duck \par
\noindent \texttt{ \ \ \ 6 } duct \par
\groupsep
\noindent \texttt{ 2451 } dude \par
\noindent \texttt{ \ \ \ 2 } dug \par
\noindent \texttt{ \ \ \ 3 } duke \par
\noindent \texttt{ \ \ \ 4 } duo \par
\noindent \texttt{ \ \ \ 5 } dusk \par
\noindent \texttt{ \ \ \ 6 } dust \par
\groupsep
\noindent \texttt{ 2461 } duty \par
\noindent \texttt{ \ \ \ 2 } dwarf \par
\noindent \texttt{ \ \ \ 3 } dwell \par
\noindent \texttt{ \ \ \ 4 } eagle \par
\noindent \texttt{ \ \ \ 5 } early \par
\noindent \texttt{ \ \ \ 6 } earth \par
\noindent \texttt{ 2511 } easel \par
\noindent \texttt{ \ \ \ 2 } east \par
\noindent \texttt{ \ \ \ 3 } eaten \par
\noindent \texttt{ \ \ \ 4 } eats \par
\noindent \texttt{ \ \ \ 5 } ebay \par
\noindent \texttt{ \ \ \ 6 } ebony \par
\groupsep
\noindent \texttt{ 2521 } ebook \par
\noindent \texttt{ \ \ \ 2 } echo \par
\noindent \texttt{ \ \ \ 3 } edge \par
\noindent \texttt{ \ \ \ 4 } eel \par
\noindent \texttt{ \ \ \ 5 } eject \par
\noindent \texttt{ \ \ \ 6 } elbow \par
\groupsep
\noindent \texttt{ 2531 } elder \par
\noindent \texttt{ \ \ \ 2 } elf \par
\noindent \texttt{ \ \ \ 3 } elk \par
\noindent \texttt{ \ \ \ 4 } elm \par
\noindent \texttt{ \ \ \ 5 } elope \par
\noindent \texttt{ \ \ \ 6 } elude \par
\groupsep
\noindent \texttt{ 2541 } elves \par
\noindent \texttt{ \ \ \ 2 } email \par
\noindent \texttt{ \ \ \ 3 } emit \par
\noindent \texttt{ \ \ \ 4 } empty \par
\noindent \texttt{ \ \ \ 5 } emu \par
\noindent \texttt{ \ \ \ 6 } enter \par
\groupsep
\noindent \texttt{ 2551 } entry \par
\noindent \texttt{ \ \ \ 2 } envoy \par
\noindent \texttt{ \ \ \ 3 } equal \par
\noindent \texttt{ \ \ \ 4 } erase \par
\noindent \texttt{ \ \ \ 5 } error \par
\noindent \texttt{ \ \ \ 6 } erupt \par
\groupsep
\noindent \texttt{ 2561 } essay \par
\noindent \texttt{ \ \ \ 2 } etch \par
\noindent \texttt{ \ \ \ 3 } evade \par
\noindent \texttt{ \ \ \ 4 } even \par
\noindent \texttt{ \ \ \ 5 } evict \par
\noindent \texttt{ \ \ \ 6 } evil \par
\noindent \texttt{ 2611 } evoke \par
\noindent \texttt{ \ \ \ 2 } exact \par
\noindent \texttt{ \ \ \ 3 } exit \par
\noindent \texttt{ \ \ \ 4 } fable \par
\noindent \texttt{ \ \ \ 5 } faced \par
\noindent \texttt{ \ \ \ 6 } fact \par
\groupsep
\noindent \texttt{ 2621 } fade \par
\noindent \texttt{ \ \ \ 2 } fall \par
\noindent \texttt{ \ \ \ 3 } false \par
\noindent \texttt{ \ \ \ 4 } fancy \par
\noindent \texttt{ \ \ \ 5 } fang \par
\noindent \texttt{ \ \ \ 6 } fax \par
\groupsep
\noindent \texttt{ 2631 } feast \par
\noindent \texttt{ \ \ \ 2 } feed \par
\noindent \texttt{ \ \ \ 3 } femur \par
\noindent \texttt{ \ \ \ 4 } fence \par
\noindent \texttt{ \ \ \ 5 } fend \par
\noindent \texttt{ \ \ \ 6 } ferry \par
\groupsep
\noindent \texttt{ 2641 } fetal \par
\noindent \texttt{ \ \ \ 2 } fetch \par
\noindent \texttt{ \ \ \ 3 } fever \par
\noindent \texttt{ \ \ \ 4 } fiber \par
\noindent \texttt{ \ \ \ 5 } fifth \par
\noindent \texttt{ \ \ \ 6 } fifty \par
\groupsep
\noindent \texttt{ 2651 } film \par
\noindent \texttt{ \ \ \ 2 } filth \par
\noindent \texttt{ \ \ \ 3 } final \par
\noindent \texttt{ \ \ \ 4 } finch \par
\noindent \texttt{ \ \ \ 5 } fit \par
\noindent \texttt{ \ \ \ 6 } five \par
\groupsep
\noindent \texttt{ 2661 } flag \par
\noindent \texttt{ \ \ \ 2 } flaky \par
\noindent \texttt{ \ \ \ 3 } flame \par
\noindent \texttt{ \ \ \ 4 } flap \par
\noindent \texttt{ \ \ \ 5 } flask \par
\noindent \texttt{ \ \ \ 6 } fled \par
\end{multicols}
\begin{multicols}{6}
\small
\noindent \texttt{ 3111 } flick \par
\noindent \texttt{ \ \ \ 2 } fling \par
\noindent \texttt{ \ \ \ 3 } flint \par
\noindent \texttt{ \ \ \ 4 } flip \par
\noindent \texttt{ \ \ \ 5 } flirt \par
\noindent \texttt{ \ \ \ 6 } float \par
\groupsep
\noindent \texttt{ 3121 } flock \par
\noindent \texttt{ \ \ \ 2 } flop \par
\noindent \texttt{ \ \ \ 3 } floss \par
\noindent \texttt{ \ \ \ 4 } flyer \par
\noindent \texttt{ \ \ \ 5 } foam \par
\noindent \texttt{ \ \ \ 6 } foe \par
\groupsep
\noindent \texttt{ 3131 } fog \par
\noindent \texttt{ \ \ \ 2 } foil \par
\noindent \texttt{ \ \ \ 3 } folic \par
\noindent \texttt{ \ \ \ 4 } folk \par
\noindent \texttt{ \ \ \ 5 } food \par
\noindent \texttt{ \ \ \ 6 } fool \par
\groupsep
\noindent \texttt{ 3141 } found \par
\noindent \texttt{ \ \ \ 2 } fox \par
\noindent \texttt{ \ \ \ 3 } foyer \par
\noindent \texttt{ \ \ \ 4 } frail \par
\noindent \texttt{ \ \ \ 5 } frame \par
\noindent \texttt{ \ \ \ 6 } fray \par
\groupsep
\noindent \texttt{ 3151 } fresh \par
\noindent \texttt{ \ \ \ 2 } fried \par
\noindent \texttt{ \ \ \ 3 } frill \par
\noindent \texttt{ \ \ \ 4 } frisk \par
\noindent \texttt{ \ \ \ 5 } from \par
\noindent \texttt{ \ \ \ 6 } front \par
\groupsep
\noindent \texttt{ 3161 } frost \par
\noindent \texttt{ \ \ \ 2 } froth \par
\noindent \texttt{ \ \ \ 3 } frown \par
\noindent \texttt{ \ \ \ 4 } froze \par
\noindent \texttt{ \ \ \ 5 } fruit \par
\noindent \texttt{ \ \ \ 6 } gag \par
\noindent \texttt{ 3211 } gains \par
\noindent \texttt{ \ \ \ 2 } gala \par
\noindent \texttt{ \ \ \ 3 } game \par
\noindent \texttt{ \ \ \ 4 } gap \par
\noindent \texttt{ \ \ \ 5 } gas \par
\noindent \texttt{ \ \ \ 6 } gave \par
\groupsep
\noindent \texttt{ 3221 } gear \par
\noindent \texttt{ \ \ \ 2 } gecko \par
\noindent \texttt{ \ \ \ 3 } geek \par
\noindent \texttt{ \ \ \ 4 } gem \par
\noindent \texttt{ \ \ \ 5 } genre \par
\noindent \texttt{ \ \ \ 6 } gift \par
\groupsep
\noindent \texttt{ 3231 } gig \par
\noindent \texttt{ \ \ \ 2 } gills \par
\noindent \texttt{ \ \ \ 3 } given \par
\noindent \texttt{ \ \ \ 4 } giver \par
\noindent \texttt{ \ \ \ 5 } glad \par
\noindent \texttt{ \ \ \ 6 } glass \par
\groupsep
\noindent \texttt{ 3241 } glide \par
\noindent \texttt{ \ \ \ 2 } gloss \par
\noindent \texttt{ \ \ \ 3 } glove \par
\noindent \texttt{ \ \ \ 4 } glow \par
\noindent \texttt{ \ \ \ 5 } glue \par
\noindent \texttt{ \ \ \ 6 } goal \par
\groupsep
\noindent \texttt{ 3251 } going \par
\noindent \texttt{ \ \ \ 2 } golf \par
\noindent \texttt{ \ \ \ 3 } gong \par
\noindent \texttt{ \ \ \ 4 } good \par
\noindent \texttt{ \ \ \ 5 } gooey \par
\noindent \texttt{ \ \ \ 6 } goofy \par
\groupsep
\noindent \texttt{ 3261 } gore \par
\noindent \texttt{ \ \ \ 2 } gown \par
\noindent \texttt{ \ \ \ 3 } grab \par
\noindent \texttt{ \ \ \ 4 } grain \par
\noindent \texttt{ \ \ \ 5 } grant \par
\noindent \texttt{ \ \ \ 6 } grape \par
\noindent \texttt{ 3311 } graph \par
\noindent \texttt{ \ \ \ 2 } grasp \par
\noindent \texttt{ \ \ \ 3 } grass \par
\noindent \texttt{ \ \ \ 4 } grave \par
\noindent \texttt{ \ \ \ 5 } gravy \par
\noindent \texttt{ \ \ \ 6 } gray \par
\groupsep
\noindent \texttt{ 3321 } green \par
\noindent \texttt{ \ \ \ 2 } greet \par
\noindent \texttt{ \ \ \ 3 } grew \par
\noindent \texttt{ \ \ \ 4 } grid \par
\noindent \texttt{ \ \ \ 5 } grief \par
\noindent \texttt{ \ \ \ 6 } grill \par
\groupsep
\noindent \texttt{ 3331 } grip \par
\noindent \texttt{ \ \ \ 2 } grit \par
\noindent \texttt{ \ \ \ 3 } groom \par
\noindent \texttt{ \ \ \ 4 } grope \par
\noindent \texttt{ \ \ \ 5 } growl \par
\noindent \texttt{ \ \ \ 6 } grub \par
\groupsep
\noindent \texttt{ 3341 } grunt \par
\noindent \texttt{ \ \ \ 2 } guide \par
\noindent \texttt{ \ \ \ 3 } gulf \par
\noindent \texttt{ \ \ \ 4 } gulp \par
\noindent \texttt{ \ \ \ 5 } gummy \par
\noindent \texttt{ \ \ \ 6 } guru \par
\groupsep
\noindent \texttt{ 3351 } gush \par
\noindent \texttt{ \ \ \ 2 } gut \par
\noindent \texttt{ \ \ \ 3 } guy \par
\noindent \texttt{ \ \ \ 4 } habit \par
\noindent \texttt{ \ \ \ 5 } half \par
\noindent \texttt{ \ \ \ 6 } halo \par
\groupsep
\noindent \texttt{ 3361 } halt \par
\noindent \texttt{ \ \ \ 2 } happy \par
\noindent \texttt{ \ \ \ 3 } harm \par
\noindent \texttt{ \ \ \ 4 } hash \par
\noindent \texttt{ \ \ \ 5 } hasty \par
\noindent \texttt{ \ \ \ 6 } hatch \par
\noindent \texttt{ 3411 } hate \par
\noindent \texttt{ \ \ \ 2 } haven \par
\noindent \texttt{ \ \ \ 3 } hazel \par
\noindent \texttt{ \ \ \ 4 } hazy \par
\noindent \texttt{ \ \ \ 5 } heap \par
\noindent \texttt{ \ \ \ 6 } heat \par
\groupsep
\noindent \texttt{ 3421 } heave \par
\noindent \texttt{ \ \ \ 2 } hedge \par
\noindent \texttt{ \ \ \ 3 } hefty \par
\noindent \texttt{ \ \ \ 4 } help \par
\noindent \texttt{ \ \ \ 5 } herbs \par
\noindent \texttt{ \ \ \ 6 } hers \par
\groupsep
\noindent \texttt{ 3431 } hub \par
\noindent \texttt{ \ \ \ 2 } hug \par
\noindent \texttt{ \ \ \ 3 } hula \par
\noindent \texttt{ \ \ \ 4 } hull \par
\noindent \texttt{ \ \ \ 5 } human \par
\noindent \texttt{ \ \ \ 6 } humid \par
\groupsep
\noindent \texttt{ 3441 } hump \par
\noindent \texttt{ \ \ \ 2 } hung \par
\noindent \texttt{ \ \ \ 3 } hunk \par
\noindent \texttt{ \ \ \ 4 } hunt \par
\noindent \texttt{ \ \ \ 5 } hurry \par
\noindent \texttt{ \ \ \ 6 } hurt \par
\groupsep
\noindent \texttt{ 3451 } hush \par
\noindent \texttt{ \ \ \ 2 } hut \par
\noindent \texttt{ \ \ \ 3 } ice \par
\noindent \texttt{ \ \ \ 4 } icing \par
\noindent \texttt{ \ \ \ 5 } icon \par
\noindent \texttt{ \ \ \ 6 } icy \par
\groupsep
\noindent \texttt{ 3461 } igloo \par
\noindent \texttt{ \ \ \ 2 } image \par
\noindent \texttt{ \ \ \ 3 } ion \par
\noindent \texttt{ \ \ \ 4 } iron \par
\noindent \texttt{ \ \ \ 5 } islam \par
\noindent \texttt{ \ \ \ 6 } issue \par
\noindent \texttt{ 3511 } item \par
\noindent \texttt{ \ \ \ 2 } ivory \par
\noindent \texttt{ \ \ \ 3 } ivy \par
\noindent \texttt{ \ \ \ 4 } jab \par
\noindent \texttt{ \ \ \ 5 } jam \par
\noindent \texttt{ \ \ \ 6 } jaws \par
\groupsep
\noindent \texttt{ 3521 } jazz \par
\noindent \texttt{ \ \ \ 2 } jeep \par
\noindent \texttt{ \ \ \ 3 } jelly \par
\noindent \texttt{ \ \ \ 4 } jet \par
\noindent \texttt{ \ \ \ 5 } jiffy \par
\noindent \texttt{ \ \ \ 6 } job \par
\groupsep
\noindent \texttt{ 3531 } jog \par
\noindent \texttt{ \ \ \ 2 } jolly \par
\noindent \texttt{ \ \ \ 3 } jolt \par
\noindent \texttt{ \ \ \ 4 } jot \par
\noindent \texttt{ \ \ \ 5 } joy \par
\noindent \texttt{ \ \ \ 6 } judge \par
\groupsep
\noindent \texttt{ 3541 } juice \par
\noindent \texttt{ \ \ \ 2 } juicy \par
\noindent \texttt{ \ \ \ 3 } july \par
\noindent \texttt{ \ \ \ 4 } jumbo \par
\noindent \texttt{ \ \ \ 5 } jump \par
\noindent \texttt{ \ \ \ 6 } junky \par
\groupsep
\noindent \texttt{ 3551 } juror \par
\noindent \texttt{ \ \ \ 2 } jury \par
\noindent \texttt{ \ \ \ 3 } keep \par
\noindent \texttt{ \ \ \ 4 } keg \par
\noindent \texttt{ \ \ \ 5 } kept \par
\noindent \texttt{ \ \ \ 6 } kick \par
\groupsep
\noindent \texttt{ 3561 } kilt \par
\noindent \texttt{ \ \ \ 2 } king \par
\noindent \texttt{ \ \ \ 3 } kite \par
\noindent \texttt{ \ \ \ 4 } kitty \par
\noindent \texttt{ \ \ \ 5 } kiwi \par
\noindent \texttt{ \ \ \ 6 } knee \par
\noindent \texttt{ 3611 } knelt \par
\noindent \texttt{ \ \ \ 2 } koala \par
\noindent \texttt{ \ \ \ 3 } kung \par
\noindent \texttt{ \ \ \ 4 } ladle \par
\noindent \texttt{ \ \ \ 5 } lady \par
\noindent \texttt{ \ \ \ 6 } lair \par
\groupsep
\noindent \texttt{ 3621 } lake \par
\noindent \texttt{ \ \ \ 2 } lance \par
\noindent \texttt{ \ \ \ 3 } land \par
\noindent \texttt{ \ \ \ 4 } lapel \par
\noindent \texttt{ \ \ \ 5 } large \par
\noindent \texttt{ \ \ \ 6 } lash \par
\groupsep
\noindent \texttt{ 3631 } lasso \par
\noindent \texttt{ \ \ \ 2 } last \par
\noindent \texttt{ \ \ \ 3 } latch \par
\noindent \texttt{ \ \ \ 4 } late \par
\noindent \texttt{ \ \ \ 5 } lazy \par
\noindent \texttt{ \ \ \ 6 } left \par
\groupsep
\noindent \texttt{ 3641 } legal \par
\noindent \texttt{ \ \ \ 2 } lemon \par
\noindent \texttt{ \ \ \ 3 } lend \par
\noindent \texttt{ \ \ \ 4 } lens \par
\noindent \texttt{ \ \ \ 5 } lent \par
\noindent \texttt{ \ \ \ 6 } level \par
\groupsep
\noindent \texttt{ 3651 } lever \par
\noindent \texttt{ \ \ \ 2 } lid \par
\noindent \texttt{ \ \ \ 3 } life \par
\noindent \texttt{ \ \ \ 4 } lift \par
\noindent \texttt{ \ \ \ 5 } lilac \par
\noindent \texttt{ \ \ \ 6 } lily \par
\groupsep
\noindent \texttt{ 3661 } limb \par
\noindent \texttt{ \ \ \ 2 } limes \par
\noindent \texttt{ \ \ \ 3 } line \par
\noindent \texttt{ \ \ \ 4 } lint \par
\noindent \texttt{ \ \ \ 5 } lion \par
\noindent \texttt{ \ \ \ 6 } lip \par
\end{multicols}
\begin{multicols}{6}
\small
\noindent \texttt{ 4111 } list \par
\noindent \texttt{ \ \ \ 2 } lived \par
\noindent \texttt{ \ \ \ 3 } liver \par
\noindent \texttt{ \ \ \ 4 } lunar \par
\noindent \texttt{ \ \ \ 5 } lunch \par
\noindent \texttt{ \ \ \ 6 } lung \par
\groupsep
\noindent \texttt{ 4121 } lurch \par
\noindent \texttt{ \ \ \ 2 } lure \par
\noindent \texttt{ \ \ \ 3 } lurk \par
\noindent \texttt{ \ \ \ 4 } lying \par
\noindent \texttt{ \ \ \ 5 } lyric \par
\noindent \texttt{ \ \ \ 6 } mace \par
\groupsep
\noindent \texttt{ 4131 } maker \par
\noindent \texttt{ \ \ \ 2 } malt \par
\noindent \texttt{ \ \ \ 3 } mama \par
\noindent \texttt{ \ \ \ 4 } mango \par
\noindent \texttt{ \ \ \ 5 } manor \par
\noindent \texttt{ \ \ \ 6 } many \par
\groupsep
\noindent \texttt{ 4141 } map \par
\noindent \texttt{ \ \ \ 2 } march \par
\noindent \texttt{ \ \ \ 3 } mardi \par
\noindent \texttt{ \ \ \ 4 } marry \par
\noindent \texttt{ \ \ \ 5 } mash \par
\noindent \texttt{ \ \ \ 6 } match \par
\groupsep
\noindent \texttt{ 4151 } mate \par
\noindent \texttt{ \ \ \ 2 } math \par
\noindent \texttt{ \ \ \ 3 } moan \par
\noindent \texttt{ \ \ \ 4 } mocha \par
\noindent \texttt{ \ \ \ 5 } moist \par
\noindent \texttt{ \ \ \ 6 } mold \par
\groupsep
\noindent \texttt{ 4161 } mom \par
\noindent \texttt{ \ \ \ 2 } moody \par
\noindent \texttt{ \ \ \ 3 } mop \par
\noindent \texttt{ \ \ \ 4 } morse \par
\noindent \texttt{ \ \ \ 5 } most \par
\noindent \texttt{ \ \ \ 6 } motor \par
\noindent \texttt{ 4211 } motto \par
\noindent \texttt{ \ \ \ 2 } mount \par
\noindent \texttt{ \ \ \ 3 } mouse \par
\noindent \texttt{ \ \ \ 4 } mousy \par
\noindent \texttt{ \ \ \ 5 } mouth \par
\noindent \texttt{ \ \ \ 6 } move \par
\groupsep
\noindent \texttt{ 4221 } movie \par
\noindent \texttt{ \ \ \ 2 } mower \par
\noindent \texttt{ \ \ \ 3 } mud \par
\noindent \texttt{ \ \ \ 4 } mug \par
\noindent \texttt{ \ \ \ 5 } mulch \par
\noindent \texttt{ \ \ \ 6 } mule \par
\groupsep
\noindent \texttt{ 4231 } mull \par
\noindent \texttt{ \ \ \ 2 } mumbo \par
\noindent \texttt{ \ \ \ 3 } mummy \par
\noindent \texttt{ \ \ \ 4 } mural \par
\noindent \texttt{ \ \ \ 5 } muse \par
\noindent \texttt{ \ \ \ 6 } music \par
\groupsep
\noindent \texttt{ 4241 } musky \par
\noindent \texttt{ \ \ \ 2 } mute \par
\noindent \texttt{ \ \ \ 3 } nacho \par
\noindent \texttt{ \ \ \ 4 } nag \par
\noindent \texttt{ \ \ \ 5 } nail \par
\noindent \texttt{ \ \ \ 6 } name \par
\groupsep
\noindent \texttt{ 4251 } nanny \par
\noindent \texttt{ \ \ \ 2 } nap \par
\noindent \texttt{ \ \ \ 3 } navy \par
\noindent \texttt{ \ \ \ 4 } near \par
\noindent \texttt{ \ \ \ 5 } neat \par
\noindent \texttt{ \ \ \ 6 } neon \par
\groupsep
\noindent \texttt{ 4261 } nerd \par
\noindent \texttt{ \ \ \ 2 } nest \par
\noindent \texttt{ \ \ \ 3 } net \par
\noindent \texttt{ \ \ \ 4 } next \par
\noindent \texttt{ \ \ \ 5 } niece \par
\noindent \texttt{ \ \ \ 6 } ninth \par
\noindent \texttt{ 4311 } nutty \par
\noindent \texttt{ \ \ \ 2 } oak \par
\noindent \texttt{ \ \ \ 3 } oasis \par
\noindent \texttt{ \ \ \ 4 } oat \par
\noindent \texttt{ \ \ \ 5 } ocean \par
\noindent \texttt{ \ \ \ 6 } oil \par
\groupsep
\noindent \texttt{ 4321 } old \par
\noindent \texttt{ \ \ \ 2 } olive \par
\noindent \texttt{ \ \ \ 3 } omen \par
\noindent \texttt{ \ \ \ 4 } onion \par
\noindent \texttt{ \ \ \ 5 } only \par
\noindent \texttt{ \ \ \ 6 } ooze \par
\groupsep
\noindent \texttt{ 4331 } opal \par
\noindent \texttt{ \ \ \ 2 } open \par
\noindent \texttt{ \ \ \ 3 } opera \par
\noindent \texttt{ \ \ \ 4 } opt \par
\noindent \texttt{ \ \ \ 5 } otter \par
\noindent \texttt{ \ \ \ 6 } ouch \par
\groupsep
\noindent \texttt{ 4341 } ounce \par
\noindent \texttt{ \ \ \ 2 } outer \par
\noindent \texttt{ \ \ \ 3 } oval \par
\noindent \texttt{ \ \ \ 4 } oven \par
\noindent \texttt{ \ \ \ 5 } owl \par
\noindent \texttt{ \ \ \ 6 } ozone \par
\groupsep
\noindent \texttt{ 4351 } pace \par
\noindent \texttt{ \ \ \ 2 } pagan \par
\noindent \texttt{ \ \ \ 3 } pager \par
\noindent \texttt{ \ \ \ 4 } palm \par
\noindent \texttt{ \ \ \ 5 } panda \par
\noindent \texttt{ \ \ \ 6 } panic \par
\groupsep
\noindent \texttt{ 4361 } pants \par
\noindent \texttt{ \ \ \ 2 } panty \par
\noindent \texttt{ \ \ \ 3 } paper \par
\noindent \texttt{ \ \ \ 4 } park \par
\noindent \texttt{ \ \ \ 5 } party \par
\noindent \texttt{ \ \ \ 6 } pasta \par
\noindent \texttt{ 4411 } patch \par
\noindent \texttt{ \ \ \ 2 } path \par
\noindent \texttt{ \ \ \ 3 } patio \par
\noindent \texttt{ \ \ \ 4 } payer \par
\noindent \texttt{ \ \ \ 5 } pecan \par
\noindent \texttt{ \ \ \ 6 } penny \par
\groupsep
\noindent \texttt{ 4421 } pep \par
\noindent \texttt{ \ \ \ 2 } perch \par
\noindent \texttt{ \ \ \ 3 } perky \par
\noindent \texttt{ \ \ \ 4 } perm \par
\noindent \texttt{ \ \ \ 5 } pest \par
\noindent \texttt{ \ \ \ 6 } petal \par
\groupsep
\noindent \texttt{ 4431 } petri \par
\noindent \texttt{ \ \ \ 2 } petty \par
\noindent \texttt{ \ \ \ 3 } photo \par
\noindent \texttt{ \ \ \ 4 } plank \par
\noindent \texttt{ \ \ \ 5 } plant \par
\noindent \texttt{ \ \ \ 6 } plaza \par
\groupsep
\noindent \texttt{ 4441 } plead \par
\noindent \texttt{ \ \ \ 2 } plot \par
\noindent \texttt{ \ \ \ 3 } plow \par
\noindent \texttt{ \ \ \ 4 } pluck \par
\noindent \texttt{ \ \ \ 5 } plug \par
\noindent \texttt{ \ \ \ 6 } plus \par
\groupsep
\noindent \texttt{ 4451 } poach \par
\noindent \texttt{ \ \ \ 2 } pod \par
\noindent \texttt{ \ \ \ 3 } poem \par
\noindent \texttt{ \ \ \ 4 } poet \par
\noindent \texttt{ \ \ \ 5 } pogo \par
\noindent \texttt{ \ \ \ 6 } point \par
\groupsep
\noindent \texttt{ 4461 } poise \par
\noindent \texttt{ \ \ \ 2 } poker \par
\noindent \texttt{ \ \ \ 3 } polar \par
\noindent \texttt{ \ \ \ 4 } polio \par
\noindent \texttt{ \ \ \ 5 } polka \par
\noindent \texttt{ \ \ \ 6 } polo \par
\noindent \texttt{ 4511 } pond \par
\noindent \texttt{ \ \ \ 2 } pony \par
\noindent \texttt{ \ \ \ 3 } poppy \par
\noindent \texttt{ \ \ \ 4 } pork \par
\noindent \texttt{ \ \ \ 5 } poser \par
\noindent \texttt{ \ \ \ 6 } pouch \par
\groupsep
\noindent \texttt{ 4521 } pound \par
\noindent \texttt{ \ \ \ 2 } pout \par
\noindent \texttt{ \ \ \ 3 } power \par
\noindent \texttt{ \ \ \ 4 } prank \par
\noindent \texttt{ \ \ \ 5 } press \par
\noindent \texttt{ \ \ \ 6 } print \par
\groupsep
\noindent \texttt{ 4531 } prior \par
\noindent \texttt{ \ \ \ 2 } prism \par
\noindent \texttt{ \ \ \ 3 } prize \par
\noindent \texttt{ \ \ \ 4 } probe \par
\noindent \texttt{ \ \ \ 5 } prong \par
\noindent \texttt{ \ \ \ 6 } proof \par
\groupsep
\noindent \texttt{ 4541 } props \par
\noindent \texttt{ \ \ \ 2 } prude \par
\noindent \texttt{ \ \ \ 3 } prune \par
\noindent \texttt{ \ \ \ 4 } pry \par
\noindent \texttt{ \ \ \ 5 } pug \par
\noindent \texttt{ \ \ \ 6 } pull \par
\groupsep
\noindent \texttt{ 4551 } pulp \par
\noindent \texttt{ \ \ \ 2 } pulse \par
\noindent \texttt{ \ \ \ 3 } puma \par
\noindent \texttt{ \ \ \ 4 } punch \par
\noindent \texttt{ \ \ \ 5 } punk \par
\noindent \texttt{ \ \ \ 6 } pupil \par
\groupsep
\noindent \texttt{ 4561 } puppy \par
\noindent \texttt{ \ \ \ 2 } purr \par
\noindent \texttt{ \ \ \ 3 } purse \par
\noindent \texttt{ \ \ \ 4 } push \par
\noindent \texttt{ \ \ \ 5 } putt \par
\noindent \texttt{ \ \ \ 6 } quack \par
\noindent \texttt{ 4611 } quake \par
\noindent \texttt{ \ \ \ 2 } query \par
\noindent \texttt{ \ \ \ 3 } quiet \par
\noindent \texttt{ \ \ \ 4 } quill \par
\noindent \texttt{ \ \ \ 5 } quilt \par
\noindent \texttt{ \ \ \ 6 } quit \par
\groupsep
\noindent \texttt{ 4621 } quota \par
\noindent \texttt{ \ \ \ 2 } quote \par
\noindent \texttt{ \ \ \ 3 } rabid \par
\noindent \texttt{ \ \ \ 4 } race \par
\noindent \texttt{ \ \ \ 5 } rack \par
\noindent \texttt{ \ \ \ 6 } radar \par
\groupsep
\noindent \texttt{ 4631 } radio \par
\noindent \texttt{ \ \ \ 2 } raft \par
\noindent \texttt{ \ \ \ 3 } rage \par
\noindent \texttt{ \ \ \ 4 } raid \par
\noindent \texttt{ \ \ \ 5 } rail \par
\noindent \texttt{ \ \ \ 6 } rake \par
\groupsep
\noindent \texttt{ 4641 } rally \par
\noindent \texttt{ \ \ \ 2 } ramp \par
\noindent \texttt{ \ \ \ 3 } ranch \par
\noindent \texttt{ \ \ \ 4 } range \par
\noindent \texttt{ \ \ \ 5 } rank \par
\noindent \texttt{ \ \ \ 6 } rant \par
\groupsep
\noindent \texttt{ 4651 } rash \par
\noindent \texttt{ \ \ \ 2 } raven \par
\noindent \texttt{ \ \ \ 3 } reach \par
\noindent \texttt{ \ \ \ 4 } react \par
\noindent \texttt{ \ \ \ 5 } ream \par
\noindent \texttt{ \ \ \ 6 } rebel \par
\groupsep
\noindent \texttt{ 4661 } recap \par
\noindent \texttt{ \ \ \ 2 } relax \par
\noindent \texttt{ \ \ \ 3 } relay \par
\noindent \texttt{ \ \ \ 4 } relic \par
\noindent \texttt{ \ \ \ 5 } remix \par
\noindent \texttt{ \ \ \ 6 } repay \par
\end{multicols}
\begin{multicols}{6}
\small
\noindent \texttt{ 5111 } repel \par
\noindent \texttt{ \ \ \ 2 } reply \par
\noindent \texttt{ \ \ \ 3 } rerun \par
\noindent \texttt{ \ \ \ 4 } reset \par
\noindent \texttt{ \ \ \ 5 } rhyme \par
\noindent \texttt{ \ \ \ 6 } rice \par
\groupsep
\noindent \texttt{ 5121 } rich \par
\noindent \texttt{ \ \ \ 2 } ride \par
\noindent \texttt{ \ \ \ 3 } rigid \par
\noindent \texttt{ \ \ \ 4 } rigor \par
\noindent \texttt{ \ \ \ 5 } rinse \par
\noindent \texttt{ \ \ \ 6 } riot \par
\groupsep
\noindent \texttt{ 5131 } ripen \par
\noindent \texttt{ \ \ \ 2 } rise \par
\noindent \texttt{ \ \ \ 3 } risk \par
\noindent \texttt{ \ \ \ 4 } ritzy \par
\noindent \texttt{ \ \ \ 5 } rival \par
\noindent \texttt{ \ \ \ 6 } river \par
\groupsep
\noindent \texttt{ 5141 } roast \par
\noindent \texttt{ \ \ \ 2 } robe \par
\noindent \texttt{ \ \ \ 3 } robin \par
\noindent \texttt{ \ \ \ 4 } rock \par
\noindent \texttt{ \ \ \ 5 } rogue \par
\noindent \texttt{ \ \ \ 6 } roman \par
\groupsep
\noindent \texttt{ 5151 } romp \par
\noindent \texttt{ \ \ \ 2 } rope \par
\noindent \texttt{ \ \ \ 3 } rover \par
\noindent \texttt{ \ \ \ 4 } royal \par
\noindent \texttt{ \ \ \ 5 } ruby \par
\noindent \texttt{ \ \ \ 6 } rug \par
\groupsep
\noindent \texttt{ 5161 } ruin \par
\noindent \texttt{ \ \ \ 2 } rule \par
\noindent \texttt{ \ \ \ 3 } runny \par
\noindent \texttt{ \ \ \ 4 } rush \par
\noindent \texttt{ \ \ \ 5 } rust \par
\noindent \texttt{ \ \ \ 6 } rut \par
\noindent \texttt{ 5211 } sadly \par
\noindent \texttt{ \ \ \ 2 } sage \par
\noindent \texttt{ \ \ \ 3 } said \par
\noindent \texttt{ \ \ \ 4 } saint \par
\noindent \texttt{ \ \ \ 5 } salad \par
\noindent \texttt{ \ \ \ 6 } salon \par
\groupsep
\noindent \texttt{ 5221 } salsa \par
\noindent \texttt{ \ \ \ 2 } salt \par
\noindent \texttt{ \ \ \ 3 } same \par
\noindent \texttt{ \ \ \ 4 } sandy \par
\noindent \texttt{ \ \ \ 5 } santa \par
\noindent \texttt{ \ \ \ 6 } satin \par
\groupsep
\noindent \texttt{ 5231 } sauna \par
\noindent \texttt{ \ \ \ 2 } saved \par
\noindent \texttt{ \ \ \ 3 } savor \par
\noindent \texttt{ \ \ \ 4 } sax \par
\noindent \texttt{ \ \ \ 5 } say \par
\noindent \texttt{ \ \ \ 6 } scale \par
\groupsep
\noindent \texttt{ 5241 } scam \par
\noindent \texttt{ \ \ \ 2 } scan \par
\noindent \texttt{ \ \ \ 3 } scare \par
\noindent \texttt{ \ \ \ 4 } scarf \par
\noindent \texttt{ \ \ \ 5 } scary \par
\noindent \texttt{ \ \ \ 6 } scoff \par
\groupsep
\noindent \texttt{ 5251 } scold \par
\noindent \texttt{ \ \ \ 2 } scoop \par
\noindent \texttt{ \ \ \ 3 } scoot \par
\noindent \texttt{ \ \ \ 4 } scope \par
\noindent \texttt{ \ \ \ 5 } score \par
\noindent \texttt{ \ \ \ 6 } scorn \par
\groupsep
\noindent \texttt{ 5261 } scout \par
\noindent \texttt{ \ \ \ 2 } scowl \par
\noindent \texttt{ \ \ \ 3 } scrap \par
\noindent \texttt{ \ \ \ 4 } scrub \par
\noindent \texttt{ \ \ \ 5 } scuba \par
\noindent \texttt{ \ \ \ 6 } scuff \par
\noindent \texttt{ 5311 } sect \par
\noindent \texttt{ \ \ \ 2 } sedan \par
\noindent \texttt{ \ \ \ 3 } self \par
\noindent \texttt{ \ \ \ 4 } send \par
\noindent \texttt{ \ \ \ 5 } sepia \par
\noindent \texttt{ \ \ \ 6 } serve \par
\groupsep
\noindent \texttt{ 5321 } set \par
\noindent \texttt{ \ \ \ 2 } seven \par
\noindent \texttt{ \ \ \ 3 } shack \par
\noindent \texttt{ \ \ \ 4 } shade \par
\noindent \texttt{ \ \ \ 5 } shady \par
\noindent \texttt{ \ \ \ 6 } shaft \par
\groupsep
\noindent \texttt{ 5331 } shaky \par
\noindent \texttt{ \ \ \ 2 } sham \par
\noindent \texttt{ \ \ \ 3 } shape \par
\noindent \texttt{ \ \ \ 4 } share \par
\noindent \texttt{ \ \ \ 5 } sharp \par
\noindent \texttt{ \ \ \ 6 } shed \par
\groupsep
\noindent \texttt{ 5341 } sheep \par
\noindent \texttt{ \ \ \ 2 } sheet \par
\noindent \texttt{ \ \ \ 3 } shelf \par
\noindent \texttt{ \ \ \ 4 } shell \par
\noindent \texttt{ \ \ \ 5 } shine \par
\noindent \texttt{ \ \ \ 6 } shiny \par
\groupsep
\noindent \texttt{ 5351 } ship \par
\noindent \texttt{ \ \ \ 2 } shirt \par
\noindent \texttt{ \ \ \ 3 } shock \par
\noindent \texttt{ \ \ \ 4 } shop \par
\noindent \texttt{ \ \ \ 5 } shore \par
\noindent \texttt{ \ \ \ 6 } shout \par
\groupsep
\noindent \texttt{ 5361 } shove \par
\noindent \texttt{ \ \ \ 2 } shown \par
\noindent \texttt{ \ \ \ 3 } showy \par
\noindent \texttt{ \ \ \ 4 } shred \par
\noindent \texttt{ \ \ \ 5 } shrug \par
\noindent \texttt{ \ \ \ 6 } shun \par
\noindent \texttt{ 5411 } shush \par
\noindent \texttt{ \ \ \ 2 } shut \par
\noindent \texttt{ \ \ \ 3 } shy \par
\noindent \texttt{ \ \ \ 4 } sift \par
\noindent \texttt{ \ \ \ 5 } silk \par
\noindent \texttt{ \ \ \ 6 } silly \par
\groupsep
\noindent \texttt{ 5421 } silo \par
\noindent \texttt{ \ \ \ 2 } sip \par
\noindent \texttt{ \ \ \ 3 } siren \par
\noindent \texttt{ \ \ \ 4 } sixth \par
\noindent \texttt{ \ \ \ 5 } size \par
\noindent \texttt{ \ \ \ 6 } skate \par
\groupsep
\noindent \texttt{ 5431 } skew \par
\noindent \texttt{ \ \ \ 2 } skid \par
\noindent \texttt{ \ \ \ 3 } skier \par
\noindent \texttt{ \ \ \ 4 } skies \par
\noindent \texttt{ \ \ \ 5 } skip \par
\noindent \texttt{ \ \ \ 6 } skirt \par
\groupsep
\noindent \texttt{ 5441 } skit \par
\noindent \texttt{ \ \ \ 2 } sky \par
\noindent \texttt{ \ \ \ 3 } slab \par
\noindent \texttt{ \ \ \ 4 } slack \par
\noindent \texttt{ \ \ \ 5 } slain \par
\noindent \texttt{ \ \ \ 6 } slam \par
\groupsep
\noindent \texttt{ 5451 } slang \par
\noindent \texttt{ \ \ \ 2 } slash \par
\noindent \texttt{ \ \ \ 3 } slate \par
\noindent \texttt{ \ \ \ 4 } slaw \par
\noindent \texttt{ \ \ \ 5 } sled \par
\noindent \texttt{ \ \ \ 6 } sleek \par
\groupsep
\noindent \texttt{ 5461 } sleep \par
\noindent \texttt{ \ \ \ 2 } sleet \par
\noindent \texttt{ \ \ \ 3 } slept \par
\noindent \texttt{ \ \ \ 4 } slice \par
\noindent \texttt{ \ \ \ 5 } slick \par
\noindent \texttt{ \ \ \ 6 } slimy \par
\noindent \texttt{ 5511 } sling \par
\noindent \texttt{ \ \ \ 2 } slip \par
\noindent \texttt{ \ \ \ 3 } slit \par
\noindent \texttt{ \ \ \ 4 } slob \par
\noindent \texttt{ \ \ \ 5 } slot \par
\noindent \texttt{ \ \ \ 6 } slug \par
\groupsep
\noindent \texttt{ 5521 } slum \par
\noindent \texttt{ \ \ \ 2 } slurp \par
\noindent \texttt{ \ \ \ 3 } slush \par
\noindent \texttt{ \ \ \ 4 } small \par
\noindent \texttt{ \ \ \ 5 } smash \par
\noindent \texttt{ \ \ \ 6 } smell \par
\groupsep
\noindent \texttt{ 5531 } smile \par
\noindent \texttt{ \ \ \ 2 } smirk \par
\noindent \texttt{ \ \ \ 3 } smog \par
\noindent \texttt{ \ \ \ 4 } snack \par
\noindent \texttt{ \ \ \ 5 } snap \par
\noindent \texttt{ \ \ \ 6 } snare \par
\groupsep
\noindent \texttt{ 5541 } snarl \par
\noindent \texttt{ \ \ \ 2 } sneak \par
\noindent \texttt{ \ \ \ 3 } sneer \par
\noindent \texttt{ \ \ \ 4 } sniff \par
\noindent \texttt{ \ \ \ 5 } snore \par
\noindent \texttt{ \ \ \ 6 } snort \par
\groupsep
\noindent \texttt{ 5551 } snout \par
\noindent \texttt{ \ \ \ 2 } snowy \par
\noindent \texttt{ \ \ \ 3 } snub \par
\noindent \texttt{ \ \ \ 4 } snuff \par
\noindent \texttt{ \ \ \ 5 } speak \par
\noindent \texttt{ \ \ \ 6 } speed \par
\groupsep
\noindent \texttt{ 5561 } spend \par
\noindent \texttt{ \ \ \ 2 } spent \par
\noindent \texttt{ \ \ \ 3 } spew \par
\noindent \texttt{ \ \ \ 4 } spied \par
\noindent \texttt{ \ \ \ 5 } spill \par
\noindent \texttt{ \ \ \ 6 } spiny \par
\noindent \texttt{ 5611 } spoil \par
\noindent \texttt{ \ \ \ 2 } spoke \par
\noindent \texttt{ \ \ \ 3 } spoof \par
\noindent \texttt{ \ \ \ 4 } spool \par
\noindent \texttt{ \ \ \ 5 } spoon \par
\noindent \texttt{ \ \ \ 6 } sport \par
\groupsep
\noindent \texttt{ 5621 } spot \par
\noindent \texttt{ \ \ \ 2 } spout \par
\noindent \texttt{ \ \ \ 3 } spray \par
\noindent \texttt{ \ \ \ 4 } spree \par
\noindent \texttt{ \ \ \ 5 } spur \par
\noindent \texttt{ \ \ \ 6 } squad \par
\groupsep
\noindent \texttt{ 5631 } squat \par
\noindent \texttt{ \ \ \ 2 } squid \par
\noindent \texttt{ \ \ \ 3 } stack \par
\noindent \texttt{ \ \ \ 4 } staff \par
\noindent \texttt{ \ \ \ 5 } stage \par
\noindent \texttt{ \ \ \ 6 } stain \par
\groupsep
\noindent \texttt{ 5641 } stall \par
\noindent \texttt{ \ \ \ 2 } stamp \par
\noindent \texttt{ \ \ \ 3 } stand \par
\noindent \texttt{ \ \ \ 4 } stank \par
\noindent \texttt{ \ \ \ 5 } stark \par
\noindent \texttt{ \ \ \ 6 } start \par
\groupsep
\noindent \texttt{ 5651 } stash \par
\noindent \texttt{ \ \ \ 2 } state \par
\noindent \texttt{ \ \ \ 3 } stays \par
\noindent \texttt{ \ \ \ 4 } steam \par
\noindent \texttt{ \ \ \ 5 } steep \par
\noindent \texttt{ \ \ \ 6 } stem \par
\groupsep
\noindent \texttt{ 5661 } step \par
\noindent \texttt{ \ \ \ 2 } stew \par
\noindent \texttt{ \ \ \ 3 } stick \par
\noindent \texttt{ \ \ \ 4 } sting \par
\noindent \texttt{ \ \ \ 5 } stir \par
\noindent \texttt{ \ \ \ 6 } stock \par
\end{multicols}
\begin{multicols}{6}
\small
\noindent \texttt{ 6111 } stole \par
\noindent \texttt{ \ \ \ 2 } stomp \par
\noindent \texttt{ \ \ \ 3 } stony \par
\noindent \texttt{ \ \ \ 4 } stood \par
\noindent \texttt{ \ \ \ 5 } stool \par
\noindent \texttt{ \ \ \ 6 } stoop \par
\groupsep
\noindent \texttt{ 6121 } stop \par
\noindent \texttt{ \ \ \ 2 } storm \par
\noindent \texttt{ \ \ \ 3 } stout \par
\noindent \texttt{ \ \ \ 4 } stove \par
\noindent \texttt{ \ \ \ 5 } straw \par
\noindent \texttt{ \ \ \ 6 } stray \par
\groupsep
\noindent \texttt{ 6131 } strut \par
\noindent \texttt{ \ \ \ 2 } stuck \par
\noindent \texttt{ \ \ \ 3 } stud \par
\noindent \texttt{ \ \ \ 4 } stuff \par
\noindent \texttt{ \ \ \ 5 } stump \par
\noindent \texttt{ \ \ \ 6 } stung \par
\groupsep
\noindent \texttt{ 6141 } stunt \par
\noindent \texttt{ \ \ \ 2 } suds \par
\noindent \texttt{ \ \ \ 3 } sugar \par
\noindent \texttt{ \ \ \ 4 } sulk \par
\noindent \texttt{ \ \ \ 5 } surf \par
\noindent \texttt{ \ \ \ 6 } sushi \par
\groupsep
\noindent \texttt{ 6151 } swab \par
\noindent \texttt{ \ \ \ 2 } swan \par
\noindent \texttt{ \ \ \ 3 } swarm \par
\noindent \texttt{ \ \ \ 4 } sway \par
\noindent \texttt{ \ \ \ 5 } swear \par
\noindent \texttt{ \ \ \ 6 } sweat \par
\groupsep
\noindent \texttt{ 6161 } sweep \par
\noindent \texttt{ \ \ \ 2 } swell \par
\noindent \texttt{ \ \ \ 3 } swept \par
\noindent \texttt{ \ \ \ 4 } swim \par
\noindent \texttt{ \ \ \ 5 } swing \par
\noindent \texttt{ \ \ \ 6 } swipe \par
\noindent \texttt{ 6211 } swirl \par
\noindent \texttt{ \ \ \ 2 } swoop \par
\noindent \texttt{ \ \ \ 3 } swore \par
\noindent \texttt{ \ \ \ 4 } syrup \par
\noindent \texttt{ \ \ \ 5 } tacky \par
\noindent \texttt{ \ \ \ 6 } taco \par
\groupsep
\noindent \texttt{ 6221 } tag \par
\noindent \texttt{ \ \ \ 2 } take \par
\noindent \texttt{ \ \ \ 3 } tall \par
\noindent \texttt{ \ \ \ 4 } talon \par
\noindent \texttt{ \ \ \ 5 } tamer \par
\noindent \texttt{ \ \ \ 6 } tank \par
\groupsep
\noindent \texttt{ 6231 } taper \par
\noindent \texttt{ \ \ \ 2 } taps \par
\noindent \texttt{ \ \ \ 3 } tarot \par
\noindent \texttt{ \ \ \ 4 } tart \par
\noindent \texttt{ \ \ \ 5 } task \par
\noindent \texttt{ \ \ \ 6 } taste \par
\groupsep
\noindent \texttt{ 6241 } tasty \par
\noindent \texttt{ \ \ \ 2 } taunt \par
\noindent \texttt{ \ \ \ 3 } thank \par
\noindent \texttt{ \ \ \ 4 } thaw \par
\noindent \texttt{ \ \ \ 5 } theft \par
\noindent \texttt{ \ \ \ 6 } theme \par
\groupsep
\noindent \texttt{ 6251 } thigh \par
\noindent \texttt{ \ \ \ 2 } thing \par
\noindent \texttt{ \ \ \ 3 } think \par
\noindent \texttt{ \ \ \ 4 } thong \par
\noindent \texttt{ \ \ \ 5 } thorn \par
\noindent \texttt{ \ \ \ 6 } those \par
\groupsep
\noindent \texttt{ 6261 } throb \par
\noindent \texttt{ \ \ \ 2 } thud \par
\noindent \texttt{ \ \ \ 3 } thumb \par
\noindent \texttt{ \ \ \ 4 } thump \par
\noindent \texttt{ \ \ \ 5 } thus \par
\noindent \texttt{ \ \ \ 6 } tiara \par
\noindent \texttt{ 6311 } tidal \par
\noindent \texttt{ \ \ \ 2 } tidy \par
\noindent \texttt{ \ \ \ 3 } tiger \par
\noindent \texttt{ \ \ \ 4 } tile \par
\noindent \texttt{ \ \ \ 5 } tilt \par
\noindent \texttt{ \ \ \ 6 } tint \par
\groupsep
\noindent \texttt{ 6321 } tiny \par
\noindent \texttt{ \ \ \ 2 } trace \par
\noindent \texttt{ \ \ \ 3 } track \par
\noindent \texttt{ \ \ \ 4 } trade \par
\noindent \texttt{ \ \ \ 5 } train \par
\noindent \texttt{ \ \ \ 6 } trait \par
\groupsep
\noindent \texttt{ 6331 } trap \par
\noindent \texttt{ \ \ \ 2 } trash \par
\noindent \texttt{ \ \ \ 3 } tray \par
\noindent \texttt{ \ \ \ 4 } treat \par
\noindent \texttt{ \ \ \ 5 } tree \par
\noindent \texttt{ \ \ \ 6 } trek \par
\groupsep
\noindent \texttt{ 6341 } trend \par
\noindent \texttt{ \ \ \ 2 } trial \par
\noindent \texttt{ \ \ \ 3 } tribe \par
\noindent \texttt{ \ \ \ 4 } trick \par
\noindent \texttt{ \ \ \ 5 } trio \par
\noindent \texttt{ \ \ \ 6 } trout \par
\groupsep
\noindent \texttt{ 6351 } truce \par
\noindent \texttt{ \ \ \ 2 } truck \par
\noindent \texttt{ \ \ \ 3 } trump \par
\noindent \texttt{ \ \ \ 4 } trunk \par
\noindent \texttt{ \ \ \ 5 } try \par
\noindent \texttt{ \ \ \ 6 } tug \par
\groupsep
\noindent \texttt{ 6361 } tulip \par
\noindent \texttt{ \ \ \ 2 } tummy \par
\noindent \texttt{ \ \ \ 3 } turf \par
\noindent \texttt{ \ \ \ 4 } tusk \par
\noindent \texttt{ \ \ \ 5 } tutor \par
\noindent \texttt{ \ \ \ 6 } tutu \par
\noindent \texttt{ 6411 } tux \par
\noindent \texttt{ \ \ \ 2 } tweak \par
\noindent \texttt{ \ \ \ 3 } tweet \par
\noindent \texttt{ \ \ \ 4 } twice \par
\noindent \texttt{ \ \ \ 5 } twine \par
\noindent \texttt{ \ \ \ 6 } twins \par
\groupsep
\noindent \texttt{ 6421 } twirl \par
\noindent \texttt{ \ \ \ 2 } twist \par
\noindent \texttt{ \ \ \ 3 } uncle \par
\noindent \texttt{ \ \ \ 4 } uncut \par
\noindent \texttt{ \ \ \ 5 } undo \par
\noindent \texttt{ \ \ \ 6 } unify \par
\groupsep
\noindent \texttt{ 6431 } union \par
\noindent \texttt{ \ \ \ 2 } unit \par
\noindent \texttt{ \ \ \ 3 } untie \par
\noindent \texttt{ \ \ \ 4 } upon \par
\noindent \texttt{ \ \ \ 5 } upper \par
\noindent \texttt{ \ \ \ 6 } urban \par
\groupsep
\noindent \texttt{ 6441 } used \par
\noindent \texttt{ \ \ \ 2 } user \par
\noindent \texttt{ \ \ \ 3 } usher \par
\noindent \texttt{ \ \ \ 4 } utter \par
\noindent \texttt{ \ \ \ 5 } value \par
\noindent \texttt{ \ \ \ 6 } vapor \par
\groupsep
\noindent \texttt{ 6451 } vegan \par
\noindent \texttt{ \ \ \ 2 } venue \par
\noindent \texttt{ \ \ \ 3 } verse \par
\noindent \texttt{ \ \ \ 4 } vest \par
\noindent \texttt{ \ \ \ 5 } veto \par
\noindent \texttt{ \ \ \ 6 } vice \par
\groupsep
\noindent \texttt{ 6461 } video \par
\noindent \texttt{ \ \ \ 2 } view \par
\noindent \texttt{ \ \ \ 3 } viral \par
\noindent \texttt{ \ \ \ 4 } virus \par
\noindent \texttt{ \ \ \ 5 } visa \par
\noindent \texttt{ \ \ \ 6 } visor \par
\noindent \texttt{ 6511 } vixen \par
\noindent \texttt{ \ \ \ 2 } vocal \par
\noindent \texttt{ \ \ \ 3 } voice \par
\noindent \texttt{ \ \ \ 4 } void \par
\noindent \texttt{ \ \ \ 5 } volt \par
\noindent \texttt{ \ \ \ 6 } voter \par
\groupsep
\noindent \texttt{ 6521 } vowel \par
\noindent \texttt{ \ \ \ 2 } wad \par
\noindent \texttt{ \ \ \ 3 } wafer \par
\noindent \texttt{ \ \ \ 4 } wager \par
\noindent \texttt{ \ \ \ 5 } wages \par
\noindent \texttt{ \ \ \ 6 } wagon \par
\groupsep
\noindent \texttt{ 6531 } wake \par
\noindent \texttt{ \ \ \ 2 } walk \par
\noindent \texttt{ \ \ \ 3 } wand \par
\noindent \texttt{ \ \ \ 4 } wasp \par
\noindent \texttt{ \ \ \ 5 } watch \par
\noindent \texttt{ \ \ \ 6 } water \par
\groupsep
\noindent \texttt{ 6541 } wavy \par
\noindent \texttt{ \ \ \ 2 } wheat \par
\noindent \texttt{ \ \ \ 3 } whiff \par
\noindent \texttt{ \ \ \ 4 } whole \par
\noindent \texttt{ \ \ \ 5 } whoop \par
\noindent \texttt{ \ \ \ 6 } wick \par
\groupsep
\noindent \texttt{ 6551 } widen \par
\noindent \texttt{ \ \ \ 2 } widow \par
\noindent \texttt{ \ \ \ 3 } width \par
\noindent \texttt{ \ \ \ 4 } wife \par
\noindent \texttt{ \ \ \ 5 } wifi \par
\noindent \texttt{ \ \ \ 6 } wilt \par
\groupsep
\noindent \texttt{ 6561 } wimp \par
\noindent \texttt{ \ \ \ 2 } wind \par
\noindent \texttt{ \ \ \ 3 } wing \par
\noindent \texttt{ \ \ \ 4 } wink \par
\noindent \texttt{ \ \ \ 5 } wipe \par
\noindent \texttt{ \ \ \ 6 } wired \par
\noindent \texttt{ 6611 } wiry \par
\noindent \texttt{ \ \ \ 2 } wise \par
\noindent \texttt{ \ \ \ 3 } wish \par
\noindent \texttt{ \ \ \ 4 } wispy \par
\noindent \texttt{ \ \ \ 5 } wok \par
\noindent \texttt{ \ \ \ 6 } wolf \par
\groupsep
\noindent \texttt{ 6621 } womb \par
\noindent \texttt{ \ \ \ 2 } wool \par
\noindent \texttt{ \ \ \ 3 } woozy \par
\noindent \texttt{ \ \ \ 4 } word \par
\noindent \texttt{ \ \ \ 5 } work \par
\noindent \texttt{ \ \ \ 6 } worry \par
\groupsep
\noindent \texttt{ 6631 } wound \par
\noindent \texttt{ \ \ \ 2 } woven \par
\noindent \texttt{ \ \ \ 3 } wrath \par
\noindent \texttt{ \ \ \ 4 } wreck \par
\noindent \texttt{ \ \ \ 5 } wrist \par
\noindent \texttt{ \ \ \ 6 } xerox \par
\groupsep
\noindent \texttt{ 6641 } yahoo \par
\noindent \texttt{ \ \ \ 2 } yam \par
\noindent \texttt{ \ \ \ 3 } yard \par
\noindent \texttt{ \ \ \ 4 } year \par
\noindent \texttt{ \ \ \ 5 } yeast \par
\noindent \texttt{ \ \ \ 6 } yelp \par
\groupsep
\noindent \texttt{ 6651 } yield \par
\noindent \texttt{ \ \ \ 2 } yo-yo \par
\noindent \texttt{ \ \ \ 3 } yodel \par
\noindent \texttt{ \ \ \ 4 } yoga \par
\noindent \texttt{ \ \ \ 5 } yoyo \par
\noindent \texttt{ \ \ \ 6 } yummy \par
\groupsep
\noindent \texttt{ 6661 } zebra \par
\noindent \texttt{ \ \ \ 2 } zero \par
\noindent \texttt{ \ \ \ 3 } zesty \par
\noindent \texttt{ \ \ \ 4 } zippy \par
\noindent \texttt{ \ \ \ 5 } zone \par
\noindent \texttt{ \ \ \ 6 } zoom \par
\end{multicols}
